[#1879] catalogus added to eigenschap/zaakinformtieobject/statustype
VNG-Realisatie/catalogi-api pull request #141
Opened 2022-07-11 09:18 UTC by MatthijsBekendam

refers to: https://github.com/VNG-Realisatie/gemma-zaken/issues/1879

2022-07-13 13:09 UTC, SonnyBA reviewed
Is het toevoegen van het `catalogus` veld nodig op de verschillende modellen? Is dit niet te herleiden uit bestaande relaties (bij `ZaakInformatieObjectType` uit bijvoorbeeld `zaaktype` of `informatieobjecttype`)?

2022-07-19 08:13 UTC, sergei-maertens commented on src/ztc/api/serializers/eigenschap.py
> +    catalogus = serializers.SerializerMethodField()
```suggestion
    catalogus = serializers.HyperlinkedRelatedField(source="zaaktype.catalogus", read_only=True)
```
should work and produce better API schema generation

2022-07-19 08:18 UTC, SonnyBA requested changes
Check nog even de comment van Sergei, volgens mij wil je hier inderdaad het `HyperlinkedRelatedField` veld voor gebruiken. Verder goed dat je gebruikt maakt van de bestaande relaties om de catalogus te tonen (ipv een nieuw veld op het model aanmaken)!

2022-07-19 08:18 UTC, SonnyBA commented on src/ztc/api/serializers/statustype.py
> +#         return method(value)
Dit kan nog even weggehaald worden ;)

2022-07-19 09:50 UTC, SonnyBA approved these changes

2022-07-19 11:01 UTC, merged